domain_path: /home/liujiawei/ALS_Silicon_Workspace/als-core/vitis_workspace/als_platform/export/als_platform/sw/standalone_psu_cortexa53_0
app_src_dir: /home/liujiawei/fpga_projects/tools/vivado/2024.1/Vitis/2024.1/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
