# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/als_system/als_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==als_system || ORIG_REF_NAME==als_system} -quiet] -quiet

# IP: bd/als_system/ip/als_system_zynq_ultra_ps_e_0_0/als_system_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==als_system_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==als_system_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/als_system/ip/als_system_axi_dma_0_0/als_system_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==als_system_axi_dma_0_0 || ORIG_REF_NAME==als_system_axi_dma_0_0} -quiet] -quiet

# IP: bd/als_system/ip/als_system_als_core_0_0/als_system_als_core_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==als_system_als_core_0_0 || ORIG_REF_NAME==als_system_als_core_0_0} -quiet] -quiet

# IP: bd/als_system/ip/als_system_rst_ps8_0_99M_0/als_system_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==als_system_rst_ps8_0_99M_0 || ORIG_REF_NAME==als_system_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/als_system/ip/als_system_ps8_0_axi_periph_0/als_system_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==als_system_ps8_0_axi_periph_0 || ORIG_REF_NAME==als_system_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/als_system/ip/als_system_axi_smc_0/als_system_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==als_system_axi_smc_0 || ORIG_REF_NAME==als_system_axi_smc_0} -quiet] -quiet

# IP: bd/als_system/ip/als_system_axis_subset_converter_0_0/als_system_axis_subset_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==als_system_axis_subset_converter_0_0 || ORIG_REF_NAME==als_system_axis_subset_converter_0_0} -quiet] -quiet

# IP: bd/als_system/ip/als_system_axis_subset_converter_1_0/als_system_axis_subset_converter_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==als_system_axis_subset_converter_1_0 || ORIG_REF_NAME==als_system_axis_subset_converter_1_0} -quiet] -quiet

# IP: bd/als_system/ip/als_system_axi_smc_1_0_7/als_system_axi_smc_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==als_system_axi_smc_1_0 || ORIG_REF_NAME==als_system_axi_smc_1_0} -quiet] -quiet

# IP: bd/als_system/ip/als_system_auto_pc_0/als_system_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==als_system_auto_pc_0 || ORIG_REF_NAME==als_system_auto_pc_0} -quiet] -quiet

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/als_system_ooc.xdc
