# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.srcs/sources_1/bd/als_system/ip/als_system_als_core_0_0/als_system_als_core_0_0.xci
# IP: The module: 'als_system_als_core_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_als_core_0_0/bc9d/als_timing.xdc
# XDC: The top module name and the constraint reference have the same name: 'als_system_als_core_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.srcs/sources_1/bd/als_system/ip/als_system_als_core_0_0/als_system_als_core_0_0.xci
# IP: The module: 'als_system_als_core_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_als_core_0_0/bc9d/als_timing.xdc
# XDC: The top module name and the constraint reference have the same name: 'als_system_als_core_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
