# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.srcs/sources_1/bd/als_system/ip/als_system_axi_smc_0/als_system_axi_smc_0.xci
# IP: The module: 'als_system_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/bd_1939.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_0/bd_1939_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_1/bd_1939_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_2/bd_1939_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_3/bd_1939_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_4/bd_1939_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_5/bd_1939_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_6/bd_1939_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_7/bd_1939_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_8/bd_1939_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_9/bd_1939_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_10/bd_1939_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_11/bd_1939_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_12/bd_1939_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_13/bd_1939_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_14/bd_1939_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_15/bd_1939_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_16/bd_1939_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_1/bd_1939_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_1/bd_1939_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_2/bd_1939_arsw_0_ooc.xdc

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_3/bd_1939_rsw_0_ooc.xdc

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_4/bd_1939_awsw_0_ooc.xdc

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_5/bd_1939_wsw_0_ooc.xdc

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_6/bd_1939_bsw_0_ooc.xdc

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_10/bd_1939_s00a2s_0_ooc.xdc

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_11/bd_1939_sarn_0_ooc.xdc

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_11/bd_1939_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_12/bd_1939_srn_0_ooc.xdc

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_12/bd_1939_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_13/bd_1939_m00s2a_0_ooc.xdc

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_14/bd_1939_m00arn_0_ooc.xdc

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_14/bd_1939_m00arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_15/bd_1939_m00rn_0_ooc.xdc

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_15/bd_1939_m00rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'als_system_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'als_system_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.srcs/sources_1/bd/als_system/ip/als_system_axi_smc_0/als_system_axi_smc_0.xci
# IP: The module: 'als_system_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/bd_1939.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_0/bd_1939_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_1/bd_1939_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_2/bd_1939_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_3/bd_1939_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_4/bd_1939_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_5/bd_1939_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_6/bd_1939_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_7/bd_1939_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_8/bd_1939_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_9/bd_1939_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_10/bd_1939_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_11/bd_1939_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_12/bd_1939_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_13/bd_1939_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_14/bd_1939_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_15/bd_1939_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_16/bd_1939_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_1/bd_1939_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_1/bd_1939_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_2/bd_1939_arsw_0_ooc.xdc

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_3/bd_1939_rsw_0_ooc.xdc

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_4/bd_1939_awsw_0_ooc.xdc

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_5/bd_1939_wsw_0_ooc.xdc

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_6/bd_1939_bsw_0_ooc.xdc

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_10/bd_1939_s00a2s_0_ooc.xdc

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_11/bd_1939_sarn_0_ooc.xdc

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_11/bd_1939_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_12/bd_1939_srn_0_ooc.xdc

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_12/bd_1939_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_13/bd_1939_m00s2a_0_ooc.xdc

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_14/bd_1939_m00arn_0_ooc.xdc

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_14/bd_1939_m00arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_15/bd_1939_m00rn_0_ooc.xdc

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/bd_0/ip/ip_15/bd_1939_m00rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'als_system_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/liujiawei/ALS_Silicon_Workspace/als-core/als_sys_project/als_sys_project.gen/sources_1/bd/als_system/ip/als_system_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'als_system_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
