domain_path: /home/liujiawei/ALS_Silicon_Workspace/als-core/vitis_workspace/als_platform/zynqmp_fsbl/zynqmp_fsbl_bsp
app_src_dir: /home/liujiawei/fpga_projects/tools/vivado/2024.1/Vitis/2024.1/data/embeddedsw/lib/sw_apps/zynqmp_fsbl
template: zynqmp_fsbl
